export const data = [
  {
    id: 0,
    cover: "/img/shoes",
    title: "White and Black",
    content: "Born in France",
    price: "120,000",
    color: "black",
  },

  {
    id: 1,
    cover: "/img/shoes",
    title: "Red Knit",
    content: "Born in Seoul",
    price: "110,000",
    color: "pink",
  },

  {
    id: 2,
    cover: "/img/shoes",
    title: "Grey Yordan",
    content: "Born in the States",
    price: "130,000",
    color: "grey",
  },
  {
    id: 3,
    cover: "/img/shoes",
    title: "Flowey",
    content: "only 5 inches",
    price: "140,000",
    color: "blue",
  },
  {
    id: 4,
    cover: "/img/shoes",
    title: "Baby shoes",
    content: "for less than 6",
    price: "90,000",
    color: "pink",
  },
  {
    id: 5,
    cover: "/img/shoes",
    title: "Red Herring",
    content: "Born in France",
    price: "95,000",
    color: "red",
  },
  {
    id: 6,
    cover: "/img/shoes",
    title: "Sijang",
    content: "from Dongmyo station",
    price: "125,000",
    color: "skyblue",
  },
  {
    id: 7,
    cover: "/img/shoes",
    title: "Tag gari",
    content: "ali and taobao",
    price: "142,000",
    color: "black",
  },
  {
    id: 8,
    cover: "/img/shoes",
    title: "Flyer",
    content: "Refund not available",
    price: "99,000",
    color: "blue",
  },
];
